npmScopes:
  midnight-ntwrk:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://npm.pkg.github.com/"
    npmRegistryServer: "https://npm.pkg.github.com/"
  midnightntwrk:
    npmRegistryServer: "https://registry.npmjs.org/"
