name: 'Publish Package Artifacts'
description: 'Publishes packages to a package registry'

inputs:
  working-directory:
    type: string
    required: true
  package-archive-name:
    type: string
    required: true
  auth-token:
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download packages artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # ratchet:actions/download-artifact@v4
      with:
        pattern: Packages ${{ inputs.package-archive-name }}
        path: ${{ inputs.working-directory }}

    - name: Extract packages archive
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: find "./Packages ${{ inputs.package-archive-name }}" -type f -name '*.zip' -execdir unzip '{}' ';'

    - name: Determine Tag
      id: vars
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        tag=$(jq -r '.v_info.tag' version.json)
        
        echo "tag=${tag}" >> "$GITHUB_OUTPUT"

    - name: Publish packages
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: find "./Packages ${{ inputs.package-archive-name }}" -type f -name '*.tgz' -execdir npm publish '{}' --tag ${{ steps.vars.outputs.tag }} --access public ';'
      env:
        GITHUB_TOKEN: ${{ inputs.auth-token }}
        NODE_AUTH_TOKEN: ${{ inputs.auth-token }}
