name: 'Publish Package Artifacts'
description: 'Publishes packages to a package registry'

inputs:
  package-archive-name:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download packages artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # ratchet:actions/download-artifact@v4
      with:
        pattern: ${{ inputs.package-archive-name }}-*.zip

    - name: Extract packages archive
      run: find . -type f -name '${{ inputs.package-archive-name }}-*.zip' | unzip -@

    - name: Publish packages
      run: find . -type f -name '*.tgz' | npm publish --access public -@
      env:
        GITHUB_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
        NODE_AUTH_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
