compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  midnight-ntwrk:
    npmAlwaysAuth: false
    npmPublishRegistry: 'https://npm.pkg.github.com/'
    npmRegistryServer: 'https://registry.npmjs.org/'

yarnPath: .yarn/releases/yarn-4.12.0.cjs

changesetBaseRefs: ['origin/main']
